variable region {}
variable vpc_name {}
variable vpc_id {}
variable vpc_cidr_block {}
variable destination_cidr_block {}
variable app_subnet_name {}
variable app_subnets {}
variable app_newbit_size {}
variable app_subnet_start {}
variable app_subnet_role {}
variable app_route_table_role {}
variable app_network_acl_name {}
variable app_network_acl_role {}
variable upsa_account_tags {}