pipeline {

    agent any

    parameters {
		
		string(name: 'role_account', defaultValue: '', description: 'role_account')
		string(name: 'role_account_name', defaultValue: '', description: 'role_account name')
        
        choice(name: 'app_env_name',
                choices: ['dev','sit','uat','prd','NA'],
                description: 'Which environment name would you like to deploy your VPC?.. Example dev')            

        choice(name: 'aws_region',
            choices: ['eu-west-3', 'eu-west-1'],
            description: 'Where would you like to deploy your VPC?.. Examples eu-west-1, eu-central-1')

        string(name: 'git_branch_name', defaultValue: '', description: 'git branch name')
		
		

        choice(name: 'env_variables',
                choices: ['paris', 'ireland'],
                description: 'Please select the variable file to apply.. Examples paris')

        choice(name: 'build_option',
            choices: ['','plan','apply', 'destroy'],
            description: 'Apply will deploy a VPC, and Destroy will remove the VPC..')


    }

    environment {

        AWS_DEFAULT_REGION = "${params.aws_region}"
        BUILD_OPTION = "${params.build_option}"
        TF_HOME = tool('terraform-0.12.12')
        TF_IN_AUTOMATION = "true"
        PATH = "$TF_HOME:$PATH"
        DIR_PATH=""

    }

    stages {

        stage('Parameters') {

            steps {

                echo "You have selected account: ${params.role_account}"
                echo "You Selected: ${params.aws_region}"



                script {
                    if("${params.app_env_name}" != "NA") {
                        echo "Environment is ${app_env_name}"
                        DIR_PATH = "terraform/accounts/${params.role_account_name}/${params.app_env_name}/ts_state_s3_dynamodb"


                    } else {
                        echo "Environment is not Applicable.."
                        DIR_PATH = "terraform/accounts/${params.role_account_name}/ts_state_s3_dynamodb"


                    }

                }                        

                


            }

        }
        
        stage('Clean the previous builds') {

            steps {
                deleteDir()
            }
        }

        stage('Checkout upsa-repo Repository') {

            steps {

                git branch: "${git_branch_name}",
                    credentialsId: 'gitlab-cred-id',
                    url: 'https://gitlab.dev.upsa.cf/Yomi.Ogunyinka/upsa-repos.git'
            }
        }

        stage('Build Phase: Plan') {

            when {

                expression {

                    params.build_option == 'plan'

                    }
                }

            steps {

                    withCredentials(
                        [
                            string(credentialsId: 'ExternalId', variable: 'external_id')
                        ]
                    )

                        {
                            echo "Applying AWS Credentials!.."

                    withAWS(credentials: 'aws-credentials',
                            region: "${params.aws_region}",
                            role:'jenkins',
                            roleAccount:"${params.role_account}",
                            externalId: "$external_id",
                            duration: 900,
                            roleSessionName: 'jenkins-session')
                        {
                            echo "This will be deployed into account ${params.role_account}"
                            echo "This will be deployed into the ${params.aws_region} region"

                            dir ("${DIR_PATH}")

                        {
                            sh "terraform -version"
                            sh "terraform init"
                            sh "terraform get"
                            sh 'terraform ${build_option} -var="region=${aws_region}" \
                                -var-file="${env_variables}".tfvars '
                        }
                    }
                }
            }
        }
        stage('Build Phase: Apply') {

            when {

                expression {

                    params.build_option == 'apply'

                    }
                }

            steps {

                    withCredentials(
                        [
                            string(credentialsId: 'ExternalId', variable: 'external_id')
                        ]
                    )

                        {
                            echo "Applying AWS Credentials!.."

                    withAWS(credentials: 'aws-credentials',
                            region: "${params.aws_region}",
                            role:'jenkins',
                            roleAccount:"${params.role_account}",
                            externalId: "$external_id",
                            duration: 900,
                            roleSessionName: 'jenkins-session')
                        {
                            echo "This will be deployed into account ${params.role_account}"
                            echo "This will be deployed into the ${params.aws_region} region"

                            dir ("${DIR_PATH}")

                        {
                            sh "terraform -version"
                            sh "terraform init"
                            sh "terraform get"
                            sh 'terraform ${build_option} -var="region=${aws_region}" \
                                -var-file=${env_variables}.tfvars -auto-approve'
                        }
                    }
                }
            }
        }
         stage('Build Phase: Destroy') {

            when {

                expression {

                    params.build_option == 'destroy'

                    }
                }

            steps {

                    withCredentials(
                        [
                            string(credentialsId: 'ExternalId', variable: 'external_id')
                        ]
                    )

                        {
                            echo "Applying AWS Credentials!.."

                    withAWS(credentials: 'aws-credentials',
                            region: "${params.aws_region}",
                            role:'jenkins',
                            roleAccount:"${params.role_account}",
                            externalId: "$external_id",
                            duration: 900,
                            roleSessionName: 'jenkins-session')
                        {
                            echo "This will be deployed into account ${params.role_account}"
                            echo "This will be deployed into the ${params.aws_region} region"

                            dir ("${DIR_PATH}")

                        {
                            sh "terraform -version"
                            sh "terraform init"
                            sh "terraform get"
                            sh 'terraform ${build_option} -var="region=${aws_region}" \
                                -var-file=${env_variables}.tfvars -auto-approve'
                        }
                    }
                }
            }
        }

    }
}
