variable region {}
variable destination_cidr_block {}
variable vpc_id {}
variable vpc_name {}
variable vpc_cidr_block {}
variable public_subnet_role {}
variable public_subnet_name {}
variable public_subnets {}
variable public_newbit_size {}
variable public_subnet_start {}
variable internet_gateway {}
variable public_route_table_role {}
variable internet_gateway_role {}
variable public_network_acl_name {}
variable public_network_acl_role {}
variable nat_gateway_name {}
variable nat_gateway_role {}
variable elastic_ip_role {}
variable upsa_account_tags {}